from app.extensions import celery, db
from app.models.drive import PlacementDrive
from app.models.application import Application
from app.models.company import Company
from app.models.report import Report
from app.models.user import User
from app.utils.mailer import send_email
from datetime import datetime
import os


def build_html_report(month, year, total_drives, total_applications, total_selected, drive_details):
    month_name = datetime(year, month, 1).strftime('%B %Y')
    generated  = datetime.now().strftime('%d %B %Y %H:%M')

    rows = ''
    for d in drive_details:
        rows += (
            '<tr>'
            '<td style="padding:8px 10px; border-bottom:1px solid #ddd;">' + str(d['job_title']) + '</td>'
            '<td style="padding:8px 10px; border-bottom:1px solid #ddd;">' + str(d['company_name']) + '</td>'
            '<td style="padding:8px 10px; border-bottom:1px solid #ddd; text-align:center;">' + str(d['applicants']) + '</td>'
            '<td style="padding:8px 10px; border-bottom:1px solid #ddd; text-align:center;">' + str(d['shortlisted']) + '</td>'
            '<td style="padding:8px 10px; border-bottom:1px solid #ddd; text-align:center;">' + str(d['selected']) + '</td>'
            '</tr>'
        )

    if not rows:
        rows = '<tr><td colspan="5" style="padding:20px; text-align:center; color:#999;">No drives conducted this month</td></tr>'

    html = '''<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <title>Monthly Placement Report - {month_name}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; color: #333; }}
        h1   {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
        h2   {{ color: #34495e; margin-top: 30px; }}
        .stats      {{ display: flex; gap: 20px; margin: 20px 0; flex-wrap: wrap; }}
        .stat-box   {{ background: #f8f9fa; border-left: 4px solid #3498db; padding: 15px 25px; border-radius: 4px; min-width: 140px; }}
        .stat-number{{ font-size: 32px; font-weight: bold; color: #2980b9; }}
        .stat-label {{ font-size: 13px; color: #666; margin-top: 4px; }}
        table  {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
        thead  {{ background: #2c3e50; color: white; }}
        th     {{ padding: 10px 12px; text-align: left; }}
        tr:nth-child(even) {{ background: #f9f9f9; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #999; }}
        .badge-green  {{ background: #27ae60; color: white; padding: 2px 8px; border-radius: 10px; font-size: 12px; }}
    </style>
</head>
<body>
    <h1>Monthly Placement Report</h1>
    <p>Period: <strong>{month_name}</strong> &nbsp; | &nbsp; Generated: {generated}</p>

    <h2>Summary</h2>
    <div class="stats">
        <div class="stat-box">
            <div class="stat-number">{total_drives}</div>
            <div class="stat-label">Drives Conducted</div>
        </div>
        <div class="stat-box">
            <div class="stat-number">{total_applications}</div>
            <div class="stat-label">Total Applications</div>
        </div>
        <div class="stat-box">
            <div class="stat-number">{total_selected}</div>
            <div class="stat-label">Students Selected</div>
        </div>
    </div>

    <h2>Drive Wise Breakdown</h2>
    <table>
        <thead>
            <tr>
                <th>Job Title</th>
                <th>Company</th>
                <th style="text-align:center;">Applicants</th>
                <th style="text-align:center;">Shortlisted</th>
                <th style="text-align:center;">Selected</th>
            </tr>
        </thead>
        <tbody>
            {rows}
        </tbody>
    </table>

    <div class="footer">
        <p>This report was auto-generated by the Placement Portal System on {generated}.</p>
        <p>Do not reply to this email.</p>
    </div>
</body>
</html>'''.format(
        month_name=month_name,
        generated=generated,
        total_drives=total_drives,
        total_applications=total_applications,
        total_selected=total_selected,
        rows=rows
    )

    return html


@celery.task(name='app.tasks.monthly_report.generate_monthly_report')
def generate_monthly_report():
    now = datetime.now()

    if now.month == 1:
        report_month = 12
        report_year  = now.year - 1
    else:
        report_month = now.month - 1
        report_year  = now.year

    existing = Report.query.filter_by(month=report_month, year=report_year).first()
    if existing:
        print('Report already exists for ' + str(report_month) + '/' + str(report_year))
        return 'Already generated'

    start = datetime(report_year, report_month, 1)
    end   = datetime(report_year + 1, 1, 1) if report_month == 12 else datetime(report_year, report_month + 1, 1)

    drives = PlacementDrive.query.filter(
        PlacementDrive.created_at >= start,
        PlacementDrive.created_at < end
    ).all()

    total_drives       = len(drives)
    total_applications = 0
    total_selected     = 0
    drive_details      = []

    for drive in drives:
        applicants  = Application.query.filter_by(drive_id=drive.id).count()
        shortlisted = Application.query.filter_by(drive_id=drive.id, status='shortlisted').count()
        selected    = Application.query.filter_by(drive_id=drive.id, status='selected').count()

        total_applications += applicants
        total_selected     += selected

        drive_details.append({
            'job_title':    drive.job_title,
            'company_name': drive.company.company_name if drive.company else 'N/A',
            'applicants':   applicants,
            'shortlisted':  shortlisted,
            'selected':     selected
        })

    html_content = build_html_report(
        report_month, report_year,
        total_drives, total_applications, total_selected,
        drive_details
    )

    from flask import current_app
    reports_dir = current_app.config['REPORTS_FOLDER']
    os.makedirs(reports_dir, exist_ok=True)

    filename = 'report_' + str(report_year) + '_' + str(report_month).zfill(2) + '.html'
    filepath = os.path.join(reports_dir, filename)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(html_content)

    report = Report(
        month=report_month,
        year=report_year,
        total_drives=total_drives,
        total_applications=total_applications,
        total_selected=total_selected,
        report_path=filename,
        sent_to_admin=False
    )
    db.session.add(report)
    db.session.commit()

    admin = User.query.filter_by(role='admin').first()
    if admin and admin.email:
        subject  = 'Monthly Placement Report - ' + datetime(report_year, report_month, 1).strftime('%B %Y')
        body     = (
            'Dear Admin,\n\n'
            'The monthly placement report for ' + datetime(report_year, report_month, 1).strftime('%B %Y') + ' is ready.\n\n'
            'Summary:\n'
            'Drives Conducted : ' + str(total_drives)       + '\n'
            'Total Applications: ' + str(total_applications) + '\n'
            'Students Selected : ' + str(total_selected)     + '\n\n'
            'Please find the full report attached as HTML.\n\n'
            'Regards,\nPlacement Portal System'
        )
        sent = send_email(admin.email, subject, body, html_body=html_content)
        if sent:
            report.sent_to_admin = True
            db.session.commit()

    print('Report generated for ' + str(report_month) + '/' + str(report_year))
    return 'Report generated: ' + filename